version: "3"
services:
  api-back:
    image: ocprojectscontainerregistry.azurecr.io/ocprojectscontainerregistry/oc-projet7-api:latest
    environment:
      DATA_PATH: '/code/data'
      MODEL_PATH: '/code/models'
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "8000:8000"
    restart: "no"
    volumes:
      - myapi-data:/code/data
      - myapi-models:/code/models
  dashboard-front:
    image: ocprojectscontainerregistry.azurecr.io/ocprojectscontainerregistry/oc-projet7-dashboard:latest
    environment:
      URL_API: "http://api-back:8000/"
    depends_on:
      - api-back
    ports:
      - "80:80"

volumes:
  myapi-data:
    driver: local
  myapi-models:
    driver: local
