version: "3"
services:
  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      DATA_PATH: '/code/data'
      MODEL_PATH: '/code/models'
    restart: always
    ports:
      - "80:80"
  dashboard:
    build: 
      context: .
      dockerfile: ./dashboard/Dockerfile
    environment:
      URL_API: "http://api:80/"
    depends_on:
      - api
    ports:
      - "8501:8501"
